---

vscode_extensions:
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-azuretools.vscode-docker
  - redhat.vscode-yaml
  - eg2.vscode-npm-script
  - scalameta.metals
  - amazonwebservices.aws-toolkit-vscode
  - 4ops.terraform
  - redhat.ansible
