---

- hosts: localhost
  connection: local
  vars_files:
    - vars/homebrew_packages.yaml
    - vars/homebrew_cask_packages.yaml

  tasks:

    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: yes

    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ homebrew_packages }}"

    - name: Install homebrew cask packages
      community.general.homebrew_cask:
        name: "{{ homebrew_cask_packages }}"