---

- hosts: localhost
  connection: local
  vars_files:
    - vars/homebrew_packages.yaml
    - vars/homebrew_cask_packages.yaml
    - vars/vscode_extensions.yaml
    - vars/pyenv_versions.yaml
    - vars/jenv_versions.yaml

  tasks:

    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ homebrew_packages }}"
        update_homebrew: yes

    - name: Install homebrew cask packages
      community.general.homebrew_cask:
        name: "{{ homebrew_cask_packages }}"

    - name: Install VSCode Extensions
      command: "code --install-extension {{ item }}"
      loop: "{{ vscode_extensions }}"
      register: vscode_results
      changed_when: "'already installed' not in vscode_results.stdout"
      failed_when: "vscode_results.rc != 0 and 'already' not in vscode_results.stdout"

    - name: Install pyenv versions
      command: "pyenv install -s {{ item }}"
      loop: "{{ pyenv_versions }}"
      register: pyenv_results
      changed_when: "pyenv_results.rc == 0 and pyenv_results.stdout != ''"

    - name: Add jenv versions
      command: "jenv add /opt/homebrew/Cellar/{{ item }}/libexec/openjdk.jdk/Contents/Home"
      loop: "{{ jenv_versions }}"
      register: jenv_results
      changed_when: "'already' not in jenv_results.stdout"
      failed_when: "jenv_results.rc != 0 and 'already' not in jenv_results.stdout"

    - name: Amend .bash_profile to source .zprofile
      blockinfile:
        path: ~/.bash_profile
        block: |
          source ~/.zshrc
        create: yes

    - name: Add config to .zshrc
      blockinfile:
        path: ~/.zshrc
        block: |
          eval "$(/opt/homebrew/bin/brew shellenv)"

          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          export PATH="$HOME/.jenv/bin:$PATH"

          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          eval "$(jenv init -)"

        create: yes

    - name: Ensure JAVA_HOME is exposed automatically
      shell: "source ~/.bash_profile && jenv enable-plugin export"
      register: java_home_results
      changed_when: "'export plugin already enabled' not in java_home_results.stdout"
      args:
        executable: /bin/zsh

    - debug:
        msg: "{{ java_home_results }}"

    - name: Install Audio apps
      community.general.homebrew_cask:
        name: "{{ homebrew_cask_audio_packages }}"
